Handle case when process.mainModule is undefined
process.mainModule is undefined when node reads from STDIN.  Do something useful by using `unknown` instead of erroring with:

```
TypeError: Cannot read property 'filename' of undefined
```